### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by unikcc** [jiekechoo/NLPStudy#2]

**Comment by jiekechoo** [comment]
有没有提示信息？@nkhouse

**Comment by unikcc** [comment]
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... not found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: edu/stanford/nlp/pipeline/StanfordCoreNLP.properties ... not found.
他为什么不去找Chinese的properties ,好像一直在找英文的，但我copy的你带代码啊

**Comment by jiekechoo** [comment]
copy 代码是是什么意思？你不是clone回去再运行吗？

**Comment by unikcc** [comment]
是clone的。。后来发现是内存JVM内存设小了，再次感谢
